import { v4 as uuidv4 } from 'uuid';
import { getDateForXDays } from '../../utils/date';

const initialState = {
  filters: [],
  sort: '',
  allExams: [
    {
      id: uuidv4(),
      subject: 'matematyka',
      unit: 'trygonometria',
      tasks: 'Rozwiązywanie z trygonometrii',
      teacher: 'Tomasz Matyski',
      date: getDateForXDays(-15),
      grade: '1',
    },
    {
      id: uuidv4(),
      subject: 'język polski',
      unit: 'Pozytywizm',
      tasks: 'Pozytywizm w Polsce - praca u podstaw i praca organiczna',
      teacher: 'Małgorzata Stanisławska',
      date: getDateForXDays(-12),
      grade: '4',
    },
    {
      id: uuidv4(),
      subject: 'matematyka',
      unit: 'równianie kwadratowe',
      tasks: 'Obliczanie delty i wyznaczenie pierwiastków',
      teacher: 'Tomasz Matyski',
      date: getDateForXDays(-10),
      grade: '2',
    },
    {
      id: uuidv4(),
      subject: 'język polski',
      unit: 'Lalka',
      tasks: 'Przebieg losów bohaterów Lalki Bolesława Prusa',
      teacher: 'Małgorzata Stanisławska',
      date: getDateForXDays(-6),
      grade: '5',
    },
    {
      id: uuidv4(),
      subject: 'historia',
      unit: 'królowie polski',
      tasks: 'Królowie z dynastii Piastów i daty ich koronacji',
      teacher: 'Halina Wielkopolska',
      date: getDateForXDays(-5),
      grade: '3',
    },
    {
      id: uuidv4(),
      subject: 'chemia',
      unit: 'kwasy',
      tasks: 'Reakcje i zastosowanie kwasów',
      teacher: 'Karolina Głogowska',
      date: getDateForXDays(-5),
      grade: '3',
    },
    {
      id: uuidv4(),
      subject: 'matematyka',
      unit: 'równianie kwadratowe',
      tasks: 'Rysowanie funkcji kwadratowych w układzie współrzędnych',
      teacher: 'Tomasz Matyski',
      date: getDateForXDays(-3),
      grade: '',
    },
    {
      id: uuidv4(),
      subject: 'historia',
      unit: 'królowie polski',
      tasks: 'Królowie z dynastii Jagiellonów i daty ich koronacji',
      teacher: 'Halina Wielkopolska',
      date: getDateForXDays(-1),
      grade: '',
    },
    {
      id: uuidv4(),
      subject: 'matematyka',
      unit: 'równianie kwadratowe',
      tasks: 'Maksymalna wartość w przedziale',
      teacher: 'Tomasz Matyski',
      date: getDateForXDays(1),
      grade: '',
    },
    {
      id: uuidv4(),
      subject: 'historia',
      unit: 'królowie polski',
      tasks: 'Jan III Sobieski i bitwa pod Wiedniem',
      teacher: 'Halina Wielkopolska',
      date: getDateForXDays(5),
      grade: '',
    },

    {
      id: uuidv4(),
      subject: 'biologia',
      unit: 'anatomia',
      tasks: 'Budowa serca i działanie układu krążenia',
      teacher: 'Maria Kałuża',
      date: getDateForXDays(15),
      grade: '',
    },
    {
      id: uuidv4(),
      subject: 'angielski',
      unit: 'Miejsce zamieszkania',
      tasks: 'Opis domu i miasta rodzinnego',
      teacher: 'Damian Tomilik',
      date: getDateForXDays(5),
      grade: '',
    },
  ],
};

export default initialState;
